// Central Region Primary Schools
export const centralPrimarySchools = [
  "Bonwapitse",
  "Ikongwe",
  "Kalamare",
  "Kgamane",
  "Kodibeleng",
  "Mmutlane",
  "Mokgenene",
  "Mokibe",
  "Moralane",
  "Mosolotshane",
  "Poloka",
  "Setlhomo",
  "Shoshong",
  "Tirelo",
  "Khurumela",
  "Boipuso",
  "Molebatsi",
  "Chakaloba",
  "Mokgware",
  "Lekadibeng",
  "Mokungwane",
  "Seolwane",
  "Radisele",
  "Morwalela",
  "Malaka",
  "Kgagodi",
  "Goosekgweng",
  "Kediretswe",
  "Lerala",
  "Mogapinyana",
  "Sebeso",
  "Tamasane",
  "Moreomabele",
  "Ratholo",
  "Moeng",
  "Mogapi",
  "Serorome",
  "Palapye Central",
  "Maunatlala",
  "Masupe",
  "Borakanelo",
  "Diloro",
  "Mogome",
  "Goo-Tau",
  "Kukubjwe",
  "Matlhakola",
  "Mapulane",
  "Lecheng",
  "Ratsie Setlhako",
  "Manaledi",
  "Lesenapole",
  "Dovedale",
  "Flowertown",
  "Fredrick",
  "Kudumatse",
  "Leetile",
  "Mahalapye primary",
  "Mmapashalala",
  "Mmuabui",
  "Moineedi",
  "Mokoswane",
  "Mokubatse",
  "Mookane",
  "Ngakayagae",
  "Nthompe Koma",
  "Pallaroad",
  "Shakwe",
  "St James",
  "St Patricks",
  "Tamocha",
  "Tewane",
  "Tshikinyega",
  "Xhosa",
  "Dimajwe",
  "Dinokwane",
  "Grace Kgari",
  "Khama Memorial",
  "Mabeleapudi",
  "Mabuo",
  "Majwanaadipitse",
  "Makolo",
  "Makolojwane",
  "Malatswae",
  "Mannathoko",
  "Mannonnye",
  "Masokola",
  "Mmashoro",
  "Mmualefhe",
  "Mogorosi",
  "Moiyabana",
  "Motalaote",
  "Motetshwane",
  "Motshegaletau",
  "Newtown",
  "Paje",
  "Riverside",
  "Sehunou",
  "Serowe central",
  "Simon Ratshosa",
  "St. Augustine",
  "St. Gabriel",
  "Thabala",
  "Tshekedi",
  "Tshimoyapula",
  "Borolong",
  "Chadibe North",
  "Foley Iteleng",
  "Gojwane",
  "Jamataka",
  "John Phooko",
  "Kgosi Sekoko I",
  "Mabesekwa",
  "Madisakwana",
  "Makobo",
  "Mandunyane",
  "Masedi",
  "Moutlwatsi",
  "Natale",
  "Rauwe",
  "Semotswane",
  "Serule",
  "Shashe Mooke",
  "Tholodi",
  "Tonota",
  "Chadibe",
  "Letoreng",
  "Maape",
  "Machaneng",
  "Matlhako",
  "Mhalapitsa",
  "Mmutle",
  "Mokobeng",
  "Mophaneng",
  "Moshopha",
  "Ngwapa",
  "Pilikwe",
  "Ramokgonami",
  "Sefhare",
  "Seleka",
  "Thabakanaka",
  "Tumasera",
  "Khumaga",
  "Letlhakane",
  "Retlhatloleng",
  "Xhumo",
  "Kedia",
  "Nicodemus",
  "Mopipi",
  "Mmadikola",
  "Tsienyane",
  "Mmatshumo",
  "Mosu",
  "Mokane",
  "Baipidi",
  "Seaseole",
  "Supang",
  "Manthabakwe",
  "Mokoboxane",
  "Motlopi",
  "Moreomaoto",
  "Toromoja",
  "Etsile",
  "Xere",
  "Mmea",
  "Khwee",
  "Mokubilo",
  "Lentswe le Moriti",
  "Tobane",
  "Tsetsebye",
  "Mafetsakgang",
  "Modisaotsile",
  "Molalatau",
  "Mathathane",
  "Busang",
  "Borotsi",
  "Letsibogo",
  "Rasetimela",
  "Robelela",
  "Agosi",
  "Gobojango",
  "Mmadinare",
  "Bobonong",
  "Phetlhu Mphoeng",
  "Moletemane",
  "ST. Peters",
  "Motsholapheko",
  "Semolale",
  "Mabolwe",
  "Tlapalakome",
  "Kelele",
  "Motlhabaneng",
  "Lepokole",
  "Mabumahubidu",
  "Madikwe",
  "Sefhophe",
  "Tshokwe",
  "Sedibe",
  "Changate",
  "Dagwi",
  "Dukwi",
  "Gasebalwe",
  "Goshwe",
  "Gweta",
  "Kutamogore",
  "Lepashe",
  "Mabuwe",
  "Magapatona",
  "Maitengwe",
  "Makongwa",
  "Makuta",
  "Mampori",
  "Manxotai",
  "Maphorisa",
  "Maposa",
  "Marapong",
  "Mathangwane",
  "Matsitlama",
  "Mengwe",
  "Mosetse",
  "Mpatane",
  "Mphinyane",
  "Mpiti",
  "Nata",
  "Nkange",
  "Nshakashogwe",
  "Nshamba",
  "Nyamambise",
  "Nswazwi",
  "Sebina",
  "Selolwane",
  "Semitwe",
  "Senete",
  "Sepako",
  "Sowa",
  "Tachibona",
  "Thini",
  "Timbi",
  "Tsokatshaa",
  "Tutume Central",
  "Dzoroga",
  "Lapologang",
  "Joseph Anderson",
  "Boitumelo",
  "Segomotso",
  "Tebogo",
  "Phikwe",
  "Boitshoko",
  "Boswelakgomo",
  "Botshabelo",
  "Tlhabololo",
  "Reuben Mpabanga"
];

// Chobe Region Primary Schools
export const chobePrimarySchools = [
  "Kavimba",
  "Mabele",
  "Kachikau",
  "Satau",
  "Parakarungu",
  "Plateau",
  "Kasane",
  "Kazungula",
  "Lesoma",
  "Pandamatenga"
];

// Ghanzi Region Primary Schools
export const ghanziPrimarySchools = [
  "Grootlaagte",
  "Kacgae",
  "Kjoe",
  "Qabo",
  "West Hanahai",
  "Chobokwane",
  "Kgaphamadi",
  "Kabakae",
  "D'kar",
  "East Hanahai",
  "Bere",
  "Kuke",
  "Gantsi",
  "New Kanagas",
  "Ncojane",
  "Makunda",
  "Kole",
  "Metsimantsho",
  "Kanagas",
  "Karakubis",
  "Boipelo P.S",
  "Kalkfontein"
];

// Kgalagadi Region Primary Schools
export const kgalagadiPrimarySchools = [
  "Bogogobo",
  "Bokspits",
  "Bopaganang",
  "Gakhibana",
  "Hereford",
  "Ikaneng",
  "Khawa",
  "Khuis",
  "Kisa",
  "Kokotsha",
  "Kolokwaneng",
  "Makopong",
  "Maleshe",
  "Maralaleng",
  "Mc Carthy's Rust",
  "Middlepits",
  "Nhake",
  "Omaweneno",
  "Rapplespan",
  "Sam MacKenzie",
  "Seetelo",
  "Struizendam",
  "Tsabong",
  "Valhoek",
  "Werda",
  "Monong",
  "Letswai",
  "Ngwatle",
  "Kang",
  "Ukhwi",
  "Hunhukwe",
  "Ncaang",
  "Mahusane",
  "Maitshoko",
  "Phuduhudu",
  "Lehututu",
  "Ledibela",
  "Mosiiwa",
  "Makgakgane",
  "Lokgwabe",
  "Tshane",
  "Inalegolo"
];

// Kgatleng Region Primary Schools
export const kgatlengPrimarySchools = [
  "Artesia",
  "Bogatsu",
  "Boiteko",
  "Dikgonnye",
  "Dikwididi",
  "Isang",
  "Kgabosereto",
  "Kgabotshwene",
  "Kgafela",
  "Kgomodiatshaba",
  "Khurutshe",
  "Lady Mitchision",
  "Leshibitse",
  "Letsebe",
  "Linchwe",
  "Mabalane",
  "Matebele",
  "Matsieng",
  "Mmadipamo",
  "Mmusi",
  "Modipane",
  "Ntshinoge",
  "Oliphants Drift",
  "Oodi",
  "Our Lady",
  "Phaphane",
  "Pilane",
  "Raditladi",
  "Ramogotsi",
  "Ramonaka",
  "Ramotlabaki",
  "Rankoa",
  "Rasesa",
  "Segale",
  "Seingwaeng",
  "Sikwane",
  "Tlhaakgame"
];

// Kweneng Region Primary Schools
export const kwenengPrimarySchools = [
  "Boatlaname",
  "Dikgatlhong",
  "Ditshukudu",
  "Gakuto",
  "Hatsalatladi",
  "Kgope",
  "Lentseletau",
  "Lephepe",
  "Leologane",
  "Letsholo",
  "Mahetlwe",
  "Makgasane",
  "Medie",
  "Mmatseta",
  "Molefe",
  "Shadishadi",
  "Sojwe",
  "Vermeleum",
  "Bakwena National",
  "Bokaa",
  "Bonweamang",
  "Borakalalo",
  "Boribamo",
  "Canon",
  "Gamodubu",
  "Kealeboga",
  "Kotolaname",
  "Kutlwano",
  "Lekgwapheng",
  "Lephaleng",
  "Lewis",
  "Louw",
  "Magokotswane",
  "Mmanoko",
  "Mogonono",
  "Monnathebe",
  "Neal Sechele",
  "Phuthadikobo",
  "Sebele",
  "Supang",
  "Botlhapatlou",
  "Diphuduhudu",
  "Ditshegwane",
  "Dutlwe",
  "Gothibamang",
  "Kaudwane",
  "Khekhenye",
  "Khudumelapye",
  "Letlhakeng",
  "Maboane",
  "Malwelwe",
  "Mantshwabisi",
  "Maratswane",
  "Metsibotlhoko",
  "Monwane",
  "Moshaweng",
  "Motokwe",
  "Ngware",
  "Salajwe",
  "Serinane",
  "Sesung",
  "Sorilatholo",
  "Takatokwane",
  "Thebephatshwa",
  "Tsetseng",
  "Tshwaane",
  "Diagane Airlink",
  "Gabane",
  "Gakgatla",
  "Gasiko",
  "Gobuamang",
  "Kontle",
  "Kubung",
  "Kumakwane",
  "Lesirane",
  "Letlole",
  "Magalatladi",
  "Metsimotlhabe",
  "Mmokolodi",
  "Mmonye",
  "Mmopane",
  "Moamogwa",
  "Mogoditshane",
  "Monare",
  "Nkoane",
  "Nkoyaphiri",
  "Pule Memorial",
  "Ramaphatle",
  "Rungwana",
  "Serameng",
  "Solomon Dihutso",
  "TauManthe",
  "Thamaga Western",
  "Tloaneng"
];

// North East Region Primary Schools
export const northEastPrimarySchools = [
  "Aerodrome",
  "Centre for Deaf",
  "Ikhutseng",
  "Lekgaba",
  "Mahube",
  "Mahudiri",
  "Maradu",
  "Mokaleng",
  "Monarch",
  "Moremogolo",
  "Ntshe",
  "Nyangabgwe",
  "Our Lady",
  "Pelotshwaana",
  "Phase IV",
  "Phatlhogo",
  "Phatsimo",
  "Satellite",
  "Tagala",
  "Tatitown",
  "Bugalo",
  "Butale",
  "Ditladi",
  "Gambule",
  "Gulubane",
  "Gungwe",
  "Jackalas 1",
  "Jackalas 2",
  "Kalakamati",
  "Kgari",
  "Legola",
  "Letsholathebe",
  "Mabudzane",
  "Makaleng",
  "Malambakwena",
  "Mambo",
  "Mapoka",
  "Masingwaneng",
  "Masukwane",
  "Masunga",
  "Matenge",
  "Matopi",
  "Matshelagabedi",
  "Matsiloje",
  "Mbalambi",
  "Moroka",
  "Mosojane",
  "Mowana",
  "Nlaphwane",
  "Patayamatebele",
  "Pelotelele",
  "Pole",
  "Ramokgwebana",
  "Sechele",
  "Sekakangwe",
  "Senyawe",
  "Siviya",
  "Tatisiding",
  "Themashanga",
  "Tsamaya",
  "Tshesebe",
  "Vukwi",
  "Zwenshambe"
];

// North West Region Primary Schools
export const northWestPrimarySchools = [
  "Ghani",
  "Mogotho",
  "Sekondomboro",
  "Gunotsoga",
  "Ngarange",
  "Shakawe",
  "Mohembo",
  "Seronga",
  "Nxamasere",
  "Kathiana",
  "Xakao",
  "Xhaoga",
  "Tsodilo",
  "Gudigwa",
  "Kauxwi",
  "Chukumuchu",
  "Samochima",
  "Beetsha",
  "Kajaja",
  "Eretsha Satelite",
  "Andrewellio",
  "Bodibeng",
  "Bonatla",
  "Boseja",
  "Botlhatlogo",
  "Botswelelo",
  "Boyei",
  "Chanoga",
  "Disaneng",
  "Gxhabara",
  "Kareng",
  "Kgosietsile",
  "Khweeosee",
  "Komana",
  "Kubung",
  "Legotlhwana",
  "Letsholathebe",
  "Makakung",
  "Makalamabedi",
  "Mathiba",
  "Matlapana",
  "Matlola",
  "Matsaudi",
  "Mogolokwane",
  "Moremi",
  "Sankoyo",
  "Sehitwa",
  "Sekgoma",
  "Semboyo",
  "Shashe",
  "Shorobe",
  "Tawana",
  "Thamalakane",
  "Thitoyamokodi",
  "Toteng",
  "Tsau",
  "Nxaraga",
  "Khwai",
  "Etsha 1",
  "Etsha 6",
  "Etsha 13",
  "Gumare",
  "Habu",
  "Ikoga",
  "Kelekele",
  "Nxaunxau",
  "Nokaneng",
  "Qangwa",
  "Sepopa",
  "Shamombo K",
  "Tlhale",
  "Tubu",
  "Xaixai"
];

// South East Region Primary Schools
export const southEastPrimarySchools = [
  "Kgomokasitwa",
  "Ben Thema",
  "Boikhutso",
  "Boitumelo",
  "Bontleng",
  "Bophirima",
  "Bosele",
  "Boswa",
  "Camp",
  "Diphetogo",
  "Galaletsang",
  "Ikageng",
  "Ithuteng",
  "Itumeleng",
  "Kgosi-Kgosi",
  "Khuduga",
  "Ledumang",
  "Lesedi",
  "Masa",
  "Marulamantsi",
  "Mophane",
  "Morula",
  "Notwane",
  "Philip Moshotle",
  "Segoditshane",
  "Taung",
  "Tlhabologo",
  "Thebe",
  "Therisanyo",
  "Thiamo",
  "Tsholofelo",
  "Tshwaragano",
  "Tsogang",
  "Mogobane",
  "Baratani",
  "Otse",
  "Ketshwerebothata",
  "Kgetheng",
  "Lesetlhana",
  "Magopane",
  "Mojadife",
  "Mokgosi",
  "Seboko",
  "Siga",
  "St. Bernads",
  "St. Condrad's",
  "Ramotswa Ceantre for Deaf",
  "St. Joseph's",
  "Batlokwa",
  "Botsalano",
  "Mafitlhakgosi"
];

// Southern Region Primary Schools
export const southernPrimarySchools = [
  "Borobadilepe",
  "Cwaanyaneng",
  "Digawana",
  "Dikhukhung",
  "Dinatshana",
  "Gamajaalela",
  "Gathwane",
  "Goodhope",
  "Gopong",
  "Kanngwe",
  "Kgoro",
  "Lejwana",
  "Leporung",
  "Logagane",
  "Lorwana",
  "Mabule",
  "Magoriapitse",
  "Maiphitlhwane",
  "Marojane",
  "Metlobo",
  "Metlojane",
  "Mmaditlou",
  "Mmakgori",
  "Mmathethe",
  "Mogojogojo",
  "Mogwalale",
  "Mokatako",
  "Mokgomane",
  "Morelelo",
  "Mosi",
  "Motsentshe",
  "Ngwatsau",
  "Phihetswana",
  "Phitshane Photlokwe",
  "Pitshane Molopo",
  "Ramatlabama",
  "Ramolefhe",
  "Sedibeng",
  "Sekhutlane",
  "Sheepfarm",
  "St Martins",
  "Tawana",
  "Tlhareseleele",
  "Tshidilamolomo",
  "Tswaaneng",
  "Tswagare",
  "Dinonyane",
  "Keng",
  "Kgalagadi",
  "Kutuku",
  "Mabutsane",
  "Mahotshwane",
  "Morwamosu",
  "Samane",
  "Sese",
  "Teemane",
  "Khakhea",
  "Betesankwe",
  "Itholoke",
  "Jwana",
  "Kanaku",
  "Khonkhwa",
  "Kokong",
  "Lefhoko",
  "Maokane",
  "Mokhomma",
  "Sekoma",
  "Thankane",
  "Tsonyane",
  "Diabo",
  "Dipotsana",
  "Gasita",
  "Ketlogetswe",
  "Khuto",
  "Logaba",
  "Lorolwane",
  "Lotlhakane",
  "Mafhikana",
  "Maisantwa",
  "Makaba II",
  "Maranyane",
  "Matlotlakgang",
  "Matsaakgang",
  "Modisi",
  "Mokgadi",
  "Molapowabojang",
  "Mosamowakwena",
  "Motsatsing",
  "Phutisutlha",
  "Pitsonyane",
  "Rachele",
  "Sebako",
  "Sebego",
  "Segopotso",
  "Segwagwa",
  "Selokolela",
  "Bothakga",
  "Hill",
  "Ipeleng",
  "Maitlamo",
  "New Look",
  "Peleng West",
  "Pitikwe",
  "St Theresa",
  "Bakgatla",
  "Bakoko",
  "Bikwe Satellite",
  "Kebonyekgotla",
  "Kgabophuti",
  "Kgabosetso",
  "Lekgolobotlo",
  "Machana Satellite",
  "Magotlhwane",
  "Manyana",
  "Mogonye",
  "Mosielele",
  "Ntlhantlhe",
  "Pitseng",
  "Polokwe",
  "Ralekgetho",
  "Ranaka",
  "Ranoi",
  "Seherelela",
  "Sesung",
  "Tshwaane"
];

// All Primary Schools (merged from all regions)
export const allPrimarySchools = [
  ...centralPrimarySchools,
  ...chobePrimarySchools,
  ...ghanziPrimarySchools,
  ...kgalagadiPrimarySchools,
  ...kgatlengPrimarySchools,
  ...kwenengPrimarySchools,
  ...northEastPrimarySchools,
  ...northWestPrimarySchools,
  ...southEastPrimarySchools,
  ...southernPrimarySchools,
  'Other'
];

// Formatted for Select components
export const allPrimarySchoolsForSelect = allPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const centralPrimarySchoolsForSelect = centralPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const chobePrimarySchoolsForSelect = chobePrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const ghanziPrimarySchoolsForSelect = ghanziPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const kgalagadiPrimarySchoolsForSelect = kgalagadiPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const kgatlengPrimarySchoolsForSelect = kgatlengPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const kwenengPrimarySchoolsForSelect = kwenengPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const northEastPrimarySchoolsForSelect = northEastPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const northWestPrimarySchoolsForSelect = northWestPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const southEastPrimarySchoolsForSelect = southEastPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));

export const southernPrimarySchoolsForSelect = southernPrimarySchools.map((school) => ({
  value: school.replace(/\s+/g, '-').replace(/['']/g, ''),
  label: school,
}));