import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Welcome",
  description: "Generated by create next app",
};

export default function WelcomeLayout({
    children, // will be a page or nested layout
  }: {
    children: React.ReactNode
  }) {
    return (
      <section>
        <nav></nav>
        {children}
      </section>
    )
  }